base_model: Medilora/medilora-usmle-textbook-adapter
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: Medilora/mimic_iii_diagnosis_anonymous
    type: completion
dataset_prepared_path: last_run_prepared
hub_model_id: medilora-mimic-adapter
val_set_size: 0.05
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - v_proj

wandb_project: medilora
wandb_entity: medilora
wandb_watch:
wandb_run_id: medilora_mimic_trial
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
eval_batch_size: 2
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 50
# eval_steps: 0.05
# eval_table_size:
# eval_table_max_new_tokens: 128
save_steps:
debug:
deepspeed: deepspeed/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

# This is not in the sample script
# Set to HF dataset for type: 'completion' for streaming instead of pre-tokenize
pretraining_dataset: