base_model: Qwen/Qwen-14B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

is_qwen_derived_model: true
trust_remote_code: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: Medilora/us_medical_license_exam_textbooks_en
    type: completion

# datasets:
#   - path: Medilora/mimic_iii_diagnosis_anonymous
#     type: completion

dataset_prepared_path:
hub_model_id: medilora_qwen_14B_completion
val_set_size: 0.05
output_dir: ./lora-out

sequence_len: 2048  # supports up to 8192
sample_packing: false
pad_to_sequence_len:

adapter: qlora
lora_model_dir:
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - v_proj


wandb_project: medilora
wandb_entity: medilora
wandb_watch:
wandb_run_id: medilora_qwen_14B_completion
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
eval_steps: 0.05
eval_table_size:
eval_table_max_new_tokens: 128
save_steps:
debug:
deepspeed: deepspeed/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
