wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.36.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700598310.591878
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 98
      3:
      - 13
      - 15
      - 23
      4: 3.11.5
      5: 0.16.0
      6: 4.36.0.dev0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
